/**
 * CNC Drilling G-code Generator
 *
 * Generates standard G-code for CNC drilling machines.
 * Compatible with Grbl, Mach3, LinuxCNC.
 *
 * Output format:
 *   G21/G90 - Metric, absolute positioning
 *   T01/M06 - Tool selection and change
 *   M03 S... - Spindle on
 *   G00 X Y  - Rapid move to hole position
 *   G00 Z... - Approach to safe plane
 *   G01 Z... - Drill plunge at feed rate
 *   G00 Z... - Retract to safe plane
 *   M05/M30  - Spindle off, end program
 */

const GCodeGenerator = (() => {

  /**
   * Generate G-code for a drilling operation.
   *
   * @param {Object} result - OptimizationResult from DrillOptimizer
   * @param {Object} tools - tools array from ExcellonParser
   * @param {Object} options - drilling parameters
   * @param {number} options.feedRate - Feed rate mm/min (default 400)
   * @param {number} options.plungeRate - Plunge rate mm/min (default 100)
   * @param {number} options.drillDepth - Drill depth mm, negative (default -2.0)
   * @param {number} options.safeHeight - Safe retract height mm (default 20)
   * @param {number} options.approachHeight - Approach height before drill (default 2)
   * @param {number} options.spindleSpeed - RPM (default 10000)
   * @param {boolean} options.useDwell - Add dwell G04 P0.1 at bottom (default false)
   * @returns {string} Complete G-code program
   */
  function generate(result, tools, options) {
    options = options || {};
    const feedRate = options.feedRate || 400;
    const plungeRate = options.plungeRate || 100;
    const drillDepth = options.drillDepth || -2.0;
    const safeHeight = options.safeHeight || 20;
    const approachHeight = options.approachHeight || 2;
    const spindleSpeed = options.spindleSpeed || 10000;
    const useDwell = options.useDwell || false;

    const lines = [];
    const holes = result.orderedHoles;
    const toolLookup = {};
    for (const t of tools) {
      toolLookup[t.number] = t;
    }

    // Header comments
    lines.push('(Generated by CNC-Tools Drill Optimizer)');
    lines.push(`(Date: ${new Date().toISOString().split('T')[0]})`);
    lines.push(`(Total holes: ${holes.length}, Tools: ${tools.length})`);
    lines.push(`(Optimized distance: ${result.totalDistance.toFixed(2)}mm, Improvement: ${result.improvement.toFixed(1)}%)`);
    lines.push('');

    // Tool table in comments
    for (const t of tools) {
      lines.push(`(T${String(t.number).padStart(2, '0')} = ${t.diameter.toFixed(3)}mm, ${t.hitCount || '?'} holes)`);
    }
    lines.push('');

    // Setup
    lines.push('G21                          (Metric)');
    lines.push('G90                          (Absolute positioning)');
    lines.push(`G00 Z${fmt(safeHeight)}               (Safe height)`);
    lines.push('');

    let currentTool = null;

    for (let i = 0; i < holes.length; i++) {
      const hole = holes[i];

      // Tool change if needed
      if (hole.tool !== currentTool) {
        if (currentTool !== null) {
          lines.push(`G00 Z${fmt(safeHeight)}`);
          lines.push('M05                          (Spindle off)');
          lines.push('');
        }

        currentTool = hole.tool;
        const toolDef = toolLookup[hole.tool];
        const diaStr = toolDef ? ` (${toolDef.diameter.toFixed(3)}mm)` : '';

        lines.push(`(--- Tool T${String(currentTool).padStart(2, '0')}${diaStr} ---)`);
        lines.push(`T${String(currentTool).padStart(2, '0')}`);
        lines.push('M06                          (Tool change)');
        lines.push(`M03 S${spindleSpeed}                   (Spindle on CW)`);
        lines.push(`G00 Z${fmt(safeHeight)}`);
        lines.push('');
      }

      // Rapid move to hole XY
      lines.push(`G00 X${fmt(hole.x)} Y${fmt(hole.y)}`);

      // Approach
      lines.push(`G00 Z${fmt(approachHeight)}`);

      // Drill plunge
      lines.push(`G01 Z${fmt(drillDepth)} F${plungeRate}`);

      // Optional dwell at bottom
      if (useDwell) {
        lines.push('G04 P0.1                    (Dwell)');
      }

      // Retract
      lines.push(`G00 Z${fmt(approachHeight)}`);
    }

    // End sequence
    lines.push('');
    lines.push(`G00 Z${fmt(safeHeight)}               (Park)`);
    lines.push('M05                          (Spindle off)');
    lines.push('G00 X0 Y0                   (Return to origin)');
    lines.push('M30                          (End program)');

    return lines.join('\n');
  }

  /**
   * Format a number for G-code output.
   * Always 3 decimal places, no trailing unnecessary zeros removed.
   */
  function fmt(value) {
    return value.toFixed(3);
  }

  /**
   * Parse G-code back into a structured representation for verification.
   * Returns array of { type, params } objects.
   */
  function parse(gcode) {
    const commands = [];
    const lines = gcode.split('\n');

    for (let i = 0; i < lines.length; i++) {
      const raw = lines[i].trim();

      // Skip empty lines and comments
      if (raw === '' || raw.startsWith('(')) continue;

      // Remove inline comments
      const code = raw.replace(/\(.*?\)/, '').trim();
      if (code === '') continue;

      // Parse G/M commands with parameters
      const tokens = code.split(/\s+/);
      const cmd = {
        line: i + 1,
        raw: raw,
        type: null,
        params: {}
      };

      for (const token of tokens) {
        const letter = token[0].toUpperCase();
        const value = parseFloat(token.substring(1));

        if (letter === 'G') {
          cmd.type = 'G' + Math.floor(value);
        } else if (letter === 'M') {
          cmd.type = 'M' + Math.floor(value);
        } else if ('XYZFSPT'.includes(letter)) {
          cmd.params[letter] = value;
        }
      }

      if (cmd.type) {
        commands.push(cmd);
      }
    }

    return commands;
  }

  /**
   * Validate G-code for common issues.
   * Returns array of warning/error strings.
   */
  function validate(gcode) {
    const issues = [];
    const commands = parse(gcode);

    let hasG21 = false;
    let hasG90 = false;
    let hasM30 = false;
    let hasSpindle = false;
    let lastZ = 0;

    for (const cmd of commands) {
      if (cmd.type === 'G21') hasG21 = true;
      if (cmd.type === 'G90') hasG90 = true;
      if (cmd.type === 'M30') hasM30 = true;
      if (cmd.type === 'M03') hasSpindle = true;

      if (cmd.params.Z !== undefined) {
        if (cmd.type === 'G01' && cmd.params.Z < -100) {
          issues.push(`Line ${cmd.line}: Unusual drill depth ${cmd.params.Z.toFixed(3)}mm (very deep)`);
        }
        lastZ = cmd.params.Z;
      }
    }

    if (!hasG21) issues.push('Warning: No G21 (metric) command found');
    if (!hasG90) issues.push('Warning: No G90 (absolute positioning) command found');
    if (!hasM30) issues.push('Warning: No M30 (end program) command found');
    if (!hasSpindle) issues.push('Warning: No M03 (spindle on) command found');

    return issues;
  }

  return {
    generate,
    parse,
    validate,
    fmt
  };
})();
