"""CNC Drilling G-code Generator.

Generates standard G-code for CNC drilling machines.
Compatible with Grbl, Mach3, LinuxCNC.
"""

from __future__ import annotations

from datetime import date
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from drill_optimizer import OptimizationResult
    from excellon_parser import DrillProject


def generate(
    result: OptimizationResult,
    project: DrillProject,
    feed_rate: float = 400.0,
    plunge_rate: float = 100.0,
    drill_depth: float = -2.0,
    safe_height: float = 20.0,
    approach_height: float = 2.0,
    spindle_speed: int = 10000,
    use_dwell: bool = False,
) -> str:
    """Generate G-code for a drilling operation."""
    lines: list[str] = []
    holes = result.ordered_holes
    tools = project.tools

    # Header
    lines.append("(Generated by CNC-Tools Drill Optimizer)")
    lines.append(f"(Date: {date.today().isoformat()})")
    lines.append(f"(Total holes: {len(holes)}, Tools: {len(tools)})")
    lines.append(f"(Optimized distance: {result.total_distance:.2f}mm, Improvement: {result.improvement:.1f}%)")
    lines.append("")
    for t in sorted(tools.values(), key=lambda t: t.number):
        lines.append(f"(T{t.number:02d} = {t.diameter:.3f}mm, {t.hit_count} holes)")
    lines.append("")

    # Setup
    lines.append("G21                          (Metric)")
    lines.append("G90                          (Absolute positioning)")
    lines.append(f"G00 Z{safe_height:.3f}               (Safe height)")
    lines.append("")

    current_tool = None
    for hole in holes:
        if hole.tool != current_tool:
            if current_tool is not None:
                lines.append(f"G00 Z{safe_height:.3f}")
                lines.append("M05                          (Spindle off)")
                lines.append("")
            current_tool = hole.tool
            td = tools.get(hole.tool)
            dia = f" ({td.diameter:.3f}mm)" if td else ""
            lines.append(f"(--- Tool T{current_tool:02d}{dia} ---)")
            lines.append(f"T{current_tool:02d}")
            lines.append("M06                          (Tool change)")
            lines.append(f"M03 S{spindle_speed}                   (Spindle on CW)")
            lines.append(f"G00 Z{safe_height:.3f}")
            lines.append("")

        lines.append(f"G00 X{hole.x:.3f} Y{hole.y:.3f}")
        lines.append(f"G00 Z{approach_height:.3f}")
        lines.append(f"G01 Z{drill_depth:.3f} F{int(plunge_rate)}")
        if use_dwell:
            lines.append("G04 P0.1                    (Dwell)")
        lines.append(f"G00 Z{approach_height:.3f}")

    # End
    lines.append("")
    lines.append(f"G00 Z{safe_height:.3f}               (Park)")
    lines.append("M05                          (Spindle off)")
    lines.append("G00 X0.000 Y0.000           (Return to origin)")
    lines.append("M30                          (End program)")

    return "\n".join(lines)
